version: "3.1"

services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0123456789
    ports: 
    - "3306:3306"
    volumes:
      - ./db/data/:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports: 
    - "6379:6379"
#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
  car-rental-web-ui:
    image: car-rental-web-ui:base
    environment:
      DB_USER: root 
      DB_PASS: 0123456789
      DB_URL: "jdbc:mysql://db:3306/car_rental?useUnicode=yes&characterEncoding=UTF-8"
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    links:
      - db
      - redis
#  ci:
#    image: jenkins
#    restart: always
#    ports: 
#    - "8081:8080"
#    - "50000:50000"
#    volumes:
#      - ./ci/data/:/var/jenkins_home